project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Shredded Cardboard Mulch"
  author: "N.A. Jelinski, M.J Smith, N.B. Pearson"
  date: "21-February-2024"
  cover-image: "cardboard-mulch-badge.png"
  
  chapters:
    - index.qmd
    - part: "Deliverables and Data Management"
      chapters:
      - deliverable1.qmd
      - deliverable2.qmd
      - deliverable3.qmd
    - part: "Results"
      chapters: 
        - results-2023.qmd 
    - part: "More Information / Get Involved"
      chapters:
        - more-info-get-involved.qmd
    - part: "Discussion Log and Meeting Minutes"
      chapters:
      - minutes-26JAN2024-check-in.qmd
      - minutes-09FEB2024-check-in.qmd
     
    # - authorship-guidelines.qmd
    # - summary.qmd
    # - references.qmd
  # appendices:
    # - co-authorship-template.qmd
    # - data-use-and-sharing.qmd

bibliography: references.bib

lightbox: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


