# Metadata for Deliverable 2: Build shared knowledge of mulching and related practices with urban growers

## Approach

To increase the use of mulch by urban growers, we will leverage co-learning gatherings. We anticipate 7-10 participants for each gathering, which support grower capacity to implement practices and create the opportunity for growers and researchers to share experiences/knowledge with each other. The Community Programming Manager (Hankerson) and UFGA (Giles, Cueto) have significant experience facilitating events and programs to support growers, and they will lead planning, coordination, and implementation for this activity. They will be supported by the graduate/undergraduate students and other members of our research team.

## Deliverables

We will work with six growers in community gardens to establish grower trials of shredded cardboard mulch, supported by a series of co-learning gatherings at each garden to build grower capacity, support implementation of mulching practices, and create space for reciprocal sharing of knowledge/experiences between community gardeners and between growers and university researchers/extension educators.
